export const stylesMui = {
  headerButton: {
    px: '24px',
    // py: '14px',
    borderRadius: '100px',
    background: '#FFC504',
    color: '#000',
    textAlign: 'center',
    fontFamily: 'Inter',
    fontSize: '16px',
    fontWeight: 500,
    textTransform: 'capitalize',
    '&:hover': {
      background: '#fff',
      color: '#FFC504',
    },
  },
  bodyButton: {
    borderRadius: '12px',
    background: '#ECC115',
    color: '#000',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: '14px',
    fontWeight: 400,
    textTransform: 'capitalize',
    whiteSpace: 'nowrap',
    '&:hover': {
      background: '#c48c00',
      color: '#000',
    },
  },
  loginButton: {
    borderRadius: '12px',
    background: '#ECC115',
    height: '3rem',
    color: '#000',
    textAlign: 'center',
    width: '100%',
    fontFamily: 'Roboto',
    fontSize: '14px',
    fontWeight: 400,
    textTransform: 'capitalize',
    whiteSpace: 'nowrap',
    '&:hover': {
      background: '#c48c00',
      color: '#000',
    },
  },
  deleteButton: {
    borderRadius: '12px',
    background: '#FF0000',
    color: '#FFFFFF',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: '14px',
    fontWeight: 400,
    textTransform: 'capitalize',
    whiteSpace: 'nowrap',
    '&:hover': {
      background: '#c48c00',
      color: '#000',
    },
  },
  suspendButton: {
    borderRadius: '12px',
    background: '#D87C0E',
    color: '#FFFFFF',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: '14px',
    fontWeight: 400,
    textTransform: 'capitalize',
    whiteSpace: 'nowrap',
    '&:hover': {
      background: '#c48c00',
      color: '#000',
    },
  },
  accountDeleteButton: {
    borderRadius: '12px',
    background: '#312828',
    color: '#FFFFFF',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: '14px',
    fontWeight: 400,
    textTransform: 'capitalize',
    whiteSpace: 'nowrap',
    '&:hover': {
      background: '#c48c00',
      color: '#000',
    },
  },
  inputField: {
    borderRadius: '12px',
    background: '#FAFBFC',
    color: '#FFFFFF',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: '14px',
    fontWeight: 400,
    textTransform: 'capitalize',
    whiteSpace: 'nowrap',
  },
  h1: {
    textAlign: 'start',
    fontFamily: 'Roboto',
    fontSize: { xs: '24px', lg: '32px' },
    lineHeight: '28px',
    fontStyle: 'normal',
    fontWeight: 700,
    textTransform: 'capitalize',
  },
  h2: {
    fontFamily: 'Roboto',
    fontSize: '24px',
    fontWeight: 700,
    lineHeight: '56px',
    textAlign: 'left',
    textTransform: 'capitalize',
  },
  h3: {
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: '18.75px',
    textTransform: 'capitalize',
  },
  sectionText: {
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: '18.75px',
    textTransform: 'capitalize',
  },
  h4: {
    fontFamily: 'Roboto',
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: '16px',
    textAlign: 'left',
    textTransform: 'uppercase',
  },
  h5: {
    fontFamily: 'Roboto',
    fontSize: '16px',
    fontWeight: 500,
    lineHeight: '18.75px',
    textAlign: 'center',
    textTransform: 'none',
  },
  h6: {
    fontFamily: 'Roboto',
    fontSize: '18px',
    fontWeight: 500,
    lineHeight: '21.09px',
    textAlign: 'center',
    textTransform: 'center',
  },
  h7: {
    fontFamily: 'Roboto',
    fontSize: '20px',
    fontWeight: 700,
    lineHeight: '23.44px',
    textAlign: 'left',
  },
  headerChipLabel: {
    fontFamily: 'Roboto',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: '16px',
    textAlign: 'left',
  },
  chipNumbers: {
    fontFamily: 'Roboto',
    fontSize: '14px',
    fontWeight: 400,
    lineHeight: '16px',
    textAlign: 'left',
  },
  airdropCountdown: {
    color: '#ECC115',
    fontFamily: 'Roboto',
    fontSize: '32px',
    fontWeight: 400,
    lineHeight: '16px',
    textAlign: 'left',
  },
}
